DevSkill.Web/Areas/Admin/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevSkill.Training.Entities;
using DevSkill.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DevSkill.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoursesController : Controller
    {
        private readonly ILogger<CoursesController> _logger;

        public CoursesController(ILogger<CoursesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var model = new CourseModel();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddOrEdit(int? id)
        {
            var model = new CourseModel();

            #region for edit
            if (id.HasValue && id != 0)
            {
                await model.LoadByIdAsync(id.Value);
            }
            #endregion

            return PartialView("_AddOrEdit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(CourseModel model)
        {
            ModelState.Remove("Id");

            if (ModelState.IsValid)
            {
                if (model.Id == null || model.Id == 0) await model.AddAsync();
                else await model.UpdateAsync();

                TempData["SuccessNotify"] = "Course has been successfully saved";
                return RedirectToAction("Index");
            }

            TempData["ErrorNotify"] = "Course could not be saved";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = new CourseModel();
            await model.DeleteAsync(id);
            return Json(true);
        }

        public async Task<IActionResult> GetCourses()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = new CourseModel();
            var data = await model.GetAllAsync(tableModel);
            return Json(data);
        }
    }
}

DevSkill.Web/Areas/Admin/Views/Courses/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<!-- Page header -->
<div class="page-header">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><a asp-controller="Dashboard" asp-action="Index" asp-area="Admin" class="text-black-50"><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Dashboard</span></a></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
            <a href="#" class="btn btn-labeled btn-labeled-right bg-primary" onclick="add_edit_Data('')">Add New <b><i class="icon-plus-circle2"></i></b></a>
        </div>
    </div>
</div>
<!-- /page header -->
<!-- Content area -->
<div class="content pt-0">

    <!-- Basic datatable -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Courses</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">

        </div>

        <table class="table" id="course-table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Seat Count</th>
                    <th>Fee</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <!-- /basic datatable -->
</div>

<!-- Add or Edit Modal -->
<div id="addOrEditModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addOrEditModalTitle">Add Course</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body" id="addOrEditModalContent"></div>

        </div>
    </div>
</div>
<!-- Add or Edit Modal -->

@section Scripts {
    <partial name="~/Views/Shared/_ValidationScriptsPartial.cshtml" />
    <partial name="~/Views/Bundle/_FormInputScriptsPartial.cshtml" />
    <partial name="~/Views/Bundle/_SweetAlertScriptsPartial.cshtml" />
    <partial name="~/Views/Bundle/_DatatableScriptsPartial.cshtml" />
    <script src="~/js/project/course.js"></script>
    <script src="~/js/ajax-call.js"></script>

    <script>
        $(function () {
            var url = '@Url.Action("GetCourses", "Courses", new { Area = "Admin" })';
            loadDatatable(url);
        });

        function delete_Data(id) {
            var url = '@Url.Action("Delete", "Courses", new { Area = "Admin" })';
            var paramData = { id: id };
            delete_confirm(url, paramData);
        }

        function add_edit_Data(id) {
            if (id !== null && id !== '') {
                $('#addOrEditModalTitle').text('Edit Course');
            } else {
                $('#addOrEditModalTitle').text('Add Course');
            }

            var url = '@Url.Action("AddOrEdit", "Courses", new { Area = "Admin" })';
            var paramData = { id: id };
            ajaxCallModal(url, paramData, "renderCourseAddOrEditLoad", "GET");
        }

        function renderCourseAddOrEditLoad(data) {
            $("#addOrEditModalContent").html(data);
            $("#addOrEditModal").modal("show");
        }
    </script>
}

DevSkill.Web/Areas/Admin/Views/Courses/_AddOrEdit.cshtml
@model CourseModel

<div class="">
    <form asp-action="AddOrEdit" id="course-form">
        <div class="">
            <fieldset class="mb-3">

                @Html.AntiForgeryToken()
                <input type="hidden" asp-for="Id" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group row">
                            <label class="col-form-label col-lg-4 required" asp-for="Title"></label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" asp-for="Title">
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-lg-4 required" asp-for="SeatCount"></label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" asp-for="SeatCount">
                                <span asp-validation-for="SeatCount" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-lg-4 required" asp-for="Fee"></label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" asp-for="Fee">
                                <span asp-validation-for="Fee" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>

            </fieldset>

        </div>
        <div class="">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-light" data-dismiss="modal"><i class="icon-close2"></i> Close</button>
                <button type="submit" class="btn bg-teal ml-2"><i class="icon-file-check2"></i> Save</button>
            </div>
        </div>
    </form>
</div>



<script>
    $.validator.unobtrusive.parse("#course-form");
</script>